/**
 * AUTO-GENERATED by scripts/sync-expui-icons.ts.
 * Source: https://github.com/JetBrains/intellij-community/tree/30e98f9c41acfd51be2ecb018c052436555b70eb
 * Do not edit this file or the vendored SVG directory by hand.
 */
import asset0Light from "./assets/jetbrains/expui/fileTypes/actionScript.svg"
import asset0Dark from "./assets/jetbrains/expui/fileTypes/actionScript_dark.svg"
import asset1Light from "./assets/jetbrains/expui/fileTypes/addAny.svg"
import asset1Dark from "./assets/jetbrains/expui/fileTypes/addAny_dark.svg"
import asset2Light from "./assets/jetbrains/expui/fileTypes/anyType.svg"
import asset2Dark from "./assets/jetbrains/expui/fileTypes/anyType_dark.svg"
import asset3Light from "./assets/jetbrains/expui/fileTypes/archive.svg"
import asset3Dark from "./assets/jetbrains/expui/fileTypes/archive_dark.svg"
import asset4Light from "./assets/jetbrains/expui/fileTypes/aspectJ.svg"
import asset4Dark from "./assets/jetbrains/expui/fileTypes/aspectJ_dark.svg"
import asset5Light from "./assets/jetbrains/expui/fileTypes/bazel.svg"
import asset5Dark from "./assets/jetbrains/expui/fileTypes/bazel_dark.svg"
import asset6Light from "./assets/jetbrains/expui/fileTypes/binaryData.svg"
import asset6Dark from "./assets/jetbrains/expui/fileTypes/binaryData_dark.svg"
import asset7Light from "./assets/jetbrains/expui/fileTypes/c.svg"
import asset7Dark from "./assets/jetbrains/expui/fileTypes/c_dark.svg"
import asset8Light from "./assets/jetbrains/expui/fileTypes/changedFile.svg"
import asset8Dark from "./assets/jetbrains/expui/fileTypes/changedFile_dark.svg"
import asset9Light from "./assets/jetbrains/expui/fileTypes/changedFiles.svg"
import asset9Dark from "./assets/jetbrains/expui/fileTypes/changedFiles_dark.svg"
import asset10Light from "./assets/jetbrains/expui/fileTypes/config.svg"
import asset10Dark from "./assets/jetbrains/expui/fileTypes/config_dark.svg"
import asset11Light from "./assets/jetbrains/expui/fileTypes/contexts.svg"
import asset11Dark from "./assets/jetbrains/expui/fileTypes/contexts_dark.svg"
import asset12Light from "./assets/jetbrains/expui/fileTypes/contextsModifier.svg"
import asset12Dark from "./assets/jetbrains/expui/fileTypes/contextsModifier_dark.svg"
import asset13Light from "./assets/jetbrains/expui/fileTypes/cpp.svg"
import asset13Dark from "./assets/jetbrains/expui/fileTypes/cpp_dark.svg"
import asset14Light from "./assets/jetbrains/expui/fileTypes/Csharp.svg"
import asset14Dark from "./assets/jetbrains/expui/fileTypes/Csharp_dark.svg"
import asset15Light from "./assets/jetbrains/expui/fileTypes/css.svg"
import asset15Dark from "./assets/jetbrains/expui/fileTypes/css_dark.svg"
import asset16Light from "./assets/jetbrains/expui/fileTypes/csv.svg"
import asset16Dark from "./assets/jetbrains/expui/fileTypes/csv_dark.svg"
import asset17Light from "./assets/jetbrains/expui/fileTypes/diagram.svg"
import asset17Dark from "./assets/jetbrains/expui/fileTypes/diagram_dark.svg"
import asset18Light from "./assets/jetbrains/expui/fileTypes/docker.svg"
import asset18Dark from "./assets/jetbrains/expui/fileTypes/docker_dark.svg"
import asset19Light from "./assets/jetbrains/expui/fileTypes/eclipse.svg"
import asset20Light from "./assets/jetbrains/expui/fileTypes/editorConfig.svg"
import asset20Dark from "./assets/jetbrains/expui/fileTypes/editorConfig_dark.svg"
import asset21Light from "./assets/jetbrains/expui/nodes/folder.svg"
import asset21Dark from "./assets/jetbrains/expui/nodes/folder_dark.svg"
import asset22Light from "./assets/jetbrains/expui/fileTypes/font.svg"
import asset22Dark from "./assets/jetbrains/expui/fileTypes/font_dark.svg"
import asset23Light from "./assets/jetbrains/expui/fileTypes/gitignore.svg"
import asset24Light from "./assets/jetbrains/language/go.svg"
import asset24Dark from "./assets/jetbrains/language/go_dark.svg"
import asset25Light from "./assets/jetbrains/expui/fileTypes/gradle.svg"
import asset25Dark from "./assets/jetbrains/expui/fileTypes/gradle_dark.svg"
import asset26Light from "./assets/jetbrains/expui/fileTypes/graphql.svg"
import asset26Dark from "./assets/jetbrains/expui/fileTypes/graphql_dark.svg"
import asset27Light from "./assets/jetbrains/expui/fileTypes/groovy.svg"
import asset27Dark from "./assets/jetbrains/expui/fileTypes/groovy_dark.svg"
import asset28Light from "./assets/jetbrains/expui/fileTypes/h.svg"
import asset28Dark from "./assets/jetbrains/expui/fileTypes/h_dark.svg"
import asset29Light from "./assets/jetbrains/expui/fileTypes/hprof.svg"
import asset29Dark from "./assets/jetbrains/expui/fileTypes/hprof_dark.svg"
import asset30Light from "./assets/jetbrains/expui/fileTypes/html.svg"
import asset30Dark from "./assets/jetbrains/expui/fileTypes/html_dark.svg"
import asset31Light from "./assets/jetbrains/expui/fileTypes/http.svg"
import asset32Light from "./assets/jetbrains/expui/fileTypes/i18n.svg"
import asset32Dark from "./assets/jetbrains/expui/fileTypes/i18n_dark.svg"
import asset33Light from "./assets/jetbrains/expui/fileTypes/ideaModule.svg"
import asset33Dark from "./assets/jetbrains/expui/fileTypes/ideaModule_dark.svg"
import asset34Light from "./assets/jetbrains/expui/fileTypes/idl.svg"
import asset34Dark from "./assets/jetbrains/expui/fileTypes/idl_dark.svg"
import asset35Light from "./assets/jetbrains/expui/fileTypes/ignored.svg"
import asset35Dark from "./assets/jetbrains/expui/fileTypes/ignored_dark.svg"
import asset36Light from "./assets/jetbrains/expui/fileTypes/image.svg"
import asset36Dark from "./assets/jetbrains/expui/fileTypes/image_dark.svg"
import asset37Light from "./assets/jetbrains/expui/fileTypes/java.svg"
import asset37Dark from "./assets/jetbrains/expui/fileTypes/java_dark.svg"
import asset38Light from "./assets/jetbrains/expui/fileTypes/javaClass.svg"
import asset38Dark from "./assets/jetbrains/expui/fileTypes/javaClass_dark.svg"
import asset39Light from "./assets/jetbrains/expui/fileTypes/javaScript.svg"
import asset39Dark from "./assets/jetbrains/expui/fileTypes/javaScript_dark.svg"
import asset40Light from "./assets/jetbrains/expui/fileTypes/jenkins.svg"
import asset41Light from "./assets/jetbrains/expui/fileTypes/jfr.svg"
import asset41Dark from "./assets/jetbrains/expui/fileTypes/jfr_dark.svg"
import asset42Light from "./assets/jetbrains/expui/fileTypes/json.svg"
import asset42Dark from "./assets/jetbrains/expui/fileTypes/json_dark.svg"
import asset43Light from "./assets/jetbrains/expui/fileTypes/jsonSchema.svg"
import asset43Dark from "./assets/jetbrains/expui/fileTypes/jsonSchema_dark.svg"
import asset44Light from "./assets/jetbrains/expui/fileTypes/jsp.svg"
import asset44Dark from "./assets/jetbrains/expui/fileTypes/jsp_dark.svg"
import asset45Light from "./assets/jetbrains/expui/fileTypes/jspx.svg"
import asset45Dark from "./assets/jetbrains/expui/fileTypes/jspx_dark.svg"
import asset46Light from "./assets/jetbrains/expui/fileTypes/jupyter.svg"
import asset46Dark from "./assets/jetbrains/expui/fileTypes/jupyter_dark.svg"
import asset47Light from "./assets/jetbrains/expui/fileTypes/manifest.svg"
import asset47Dark from "./assets/jetbrains/expui/fileTypes/manifest_dark.svg"
import asset48Light from "./assets/jetbrains/expui/fileTypes/markdown.svg"
import asset48Dark from "./assets/jetbrains/expui/fileTypes/markdown_dark.svg"
import asset49Light from "./assets/jetbrains/expui/fileTypes/microsoftWindows.svg"
import asset49Dark from "./assets/jetbrains/expui/fileTypes/microsoftWindows_dark.svg"
import asset50Light from "./assets/jetbrains/expui/fileTypes/modified.svg"
import asset50Dark from "./assets/jetbrains/expui/fileTypes/modified_dark.svg"
import asset51Light from "./assets/jetbrains/expui/fileTypes/patch.svg"
import asset51Dark from "./assets/jetbrains/expui/fileTypes/patch_dark.svg"
import asset52Light from "./assets/jetbrains/expui/fileTypes/perl.svg"
import asset52Dark from "./assets/jetbrains/expui/fileTypes/perl_dark.svg"
import asset53Light from "./assets/jetbrains/expui/fileTypes/properties.svg"
import asset53Dark from "./assets/jetbrains/expui/fileTypes/properties_dark.svg"
import asset54Light from "./assets/jetbrains/language/python.svg"
import asset54Dark from "./assets/jetbrains/language/python_dark.svg"
import asset55Light from "./assets/jetbrains/expui/fileTypes/regexp.svg"
import asset55Dark from "./assets/jetbrains/expui/fileTypes/regexp_dark.svg"
import asset56Light from "./assets/jetbrains/expui/fileTypes/rst.svg"
import asset56Dark from "./assets/jetbrains/expui/fileTypes/rst_dark.svg"
import asset57Light from "./assets/jetbrains/language/rust.svg"
import asset57Dark from "./assets/jetbrains/language/rust_dark.svg"
import asset58Light from "./assets/jetbrains/expui/fileTypes/scratch.svg"
import asset58Dark from "./assets/jetbrains/expui/fileTypes/scratch_dark.svg"
import asset59Light from "./assets/jetbrains/expui/fileTypes/scratches.svg"
import asset59Dark from "./assets/jetbrains/expui/fileTypes/scratches_dark.svg"
import asset60Light from "./assets/jetbrains/expui/fileTypes/shell.svg"
import asset60Dark from "./assets/jetbrains/expui/fileTypes/shell_dark.svg"
import asset61Light from "./assets/jetbrains/expui/fileTypes/sourceMap.svg"
import asset61Dark from "./assets/jetbrains/expui/fileTypes/sourceMap_dark.svg"
import asset62Light from "./assets/jetbrains/expui/fileTypes/sql.svg"
import asset62Dark from "./assets/jetbrains/expui/fileTypes/sql_dark.svg"
import asset63Light from "./assets/jetbrains/expui/fileTypes/swiftLang.svg"
import asset63Dark from "./assets/jetbrains/expui/fileTypes/swiftLang_dark.svg"
import asset64Light from "./assets/jetbrains/expui/fileTypes/terraform.svg"
import asset64Dark from "./assets/jetbrains/expui/fileTypes/terraform_dark.svg"
import asset65Light from "./assets/jetbrains/expui/fileTypes/text.svg"
import asset65Dark from "./assets/jetbrains/expui/fileTypes/text_dark.svg"
import asset66Light from "./assets/jetbrains/expui/fileTypes/toml.svg"
import asset66Dark from "./assets/jetbrains/expui/fileTypes/toml_dark.svg"
import asset67Light from "./assets/jetbrains/expui/fileTypes/typeScript.svg"
import asset67Dark from "./assets/jetbrains/expui/fileTypes/typeScript_dark.svg"
import asset68Light from "./assets/jetbrains/expui/fileTypes/uiForm.svg"
import asset68Dark from "./assets/jetbrains/expui/fileTypes/uiForm_dark.svg"
import asset69Light from "./assets/jetbrains/expui/fileTypes/unknown.svg"
import asset69Dark from "./assets/jetbrains/expui/fileTypes/unknown_dark.svg"
import asset70Light from "./assets/jetbrains/expui/fileTypes/vue.svg"
import asset71Light from "./assets/jetbrains/expui/fileTypes/wsdl.svg"
import asset71Dark from "./assets/jetbrains/expui/fileTypes/wsdl_dark.svg"
import asset72Light from "./assets/jetbrains/expui/fileTypes/xhtml.svg"
import asset72Dark from "./assets/jetbrains/expui/fileTypes/xhtml_dark.svg"
import asset73Light from "./assets/jetbrains/expui/fileTypes/xml.svg"
import asset73Dark from "./assets/jetbrains/expui/fileTypes/xml_dark.svg"
import asset74Light from "./assets/jetbrains/expui/fileTypes/xsd.svg"
import asset74Dark from "./assets/jetbrains/expui/fileTypes/xsd_dark.svg"
import asset75Light from "./assets/jetbrains/expui/fileTypes/yaml.svg"
import asset75Dark from "./assets/jetbrains/expui/fileTypes/yaml_dark.svg"

export interface IconAssetSources {
  readonly light: string
  readonly dark: string
}

function dataUrl(source: string): string {
  return `data:image/svg+xml,${encodeURIComponent(source)}`
}

function pair(light: string, dark: string): IconAssetSources {
  return { light: dataUrl(light), dark: dataUrl(dark) }
}

export const ICON_ASSETS = {
  "actionScript": pair(asset0Light, asset0Dark),
  "addAny": pair(asset1Light, asset1Dark),
  "anyType": pair(asset2Light, asset2Dark),
  "archive": pair(asset3Light, asset3Dark),
  "aspectJ": pair(asset4Light, asset4Dark),
  "bazel": pair(asset5Light, asset5Dark),
  "binaryData": pair(asset6Light, asset6Dark),
  "c": pair(asset7Light, asset7Dark),
  "changedFile": pair(asset8Light, asset8Dark),
  "changedFiles": pair(asset9Light, asset9Dark),
  "config": pair(asset10Light, asset10Dark),
  "contexts": pair(asset11Light, asset11Dark),
  "contextsModifier": pair(asset12Light, asset12Dark),
  "cpp": pair(asset13Light, asset13Dark),
  "Csharp": pair(asset14Light, asset14Dark),
  "css": pair(asset15Light, asset15Dark),
  "csv": pair(asset16Light, asset16Dark),
  "diagram": pair(asset17Light, asset17Dark),
  "docker": pair(asset18Light, asset18Dark),
  "eclipse": pair(asset19Light, asset19Light),
  "editorConfig": pair(asset20Light, asset20Dark),
  "folder": pair(asset21Light, asset21Dark),
  "font": pair(asset22Light, asset22Dark),
  "gitignore": pair(asset23Light, asset23Light),
  "go": pair(asset24Light, asset24Dark),
  "gradle": pair(asset25Light, asset25Dark),
  "graphql": pair(asset26Light, asset26Dark),
  "groovy": pair(asset27Light, asset27Dark),
  "h": pair(asset28Light, asset28Dark),
  "hprof": pair(asset29Light, asset29Dark),
  "html": pair(asset30Light, asset30Dark),
  "http": pair(asset31Light, asset31Light),
  "i18n": pair(asset32Light, asset32Dark),
  "ideaModule": pair(asset33Light, asset33Dark),
  "idl": pair(asset34Light, asset34Dark),
  "ignored": pair(asset35Light, asset35Dark),
  "image": pair(asset36Light, asset36Dark),
  "java": pair(asset37Light, asset37Dark),
  "javaClass": pair(asset38Light, asset38Dark),
  "javaScript": pair(asset39Light, asset39Dark),
  "jenkins": pair(asset40Light, asset40Light),
  "jfr": pair(asset41Light, asset41Dark),
  "json": pair(asset42Light, asset42Dark),
  "jsonSchema": pair(asset43Light, asset43Dark),
  "jsp": pair(asset44Light, asset44Dark),
  "jspx": pair(asset45Light, asset45Dark),
  "jupyter": pair(asset46Light, asset46Dark),
  "manifest": pair(asset47Light, asset47Dark),
  "markdown": pair(asset48Light, asset48Dark),
  "microsoftWindows": pair(asset49Light, asset49Dark),
  "modified": pair(asset50Light, asset50Dark),
  "patch": pair(asset51Light, asset51Dark),
  "perl": pair(asset52Light, asset52Dark),
  "properties": pair(asset53Light, asset53Dark),
  "python": pair(asset54Light, asset54Dark),
  "regexp": pair(asset55Light, asset55Dark),
  "rst": pair(asset56Light, asset56Dark),
  "rust": pair(asset57Light, asset57Dark),
  "scratch": pair(asset58Light, asset58Dark),
  "scratches": pair(asset59Light, asset59Dark),
  "shell": pair(asset60Light, asset60Dark),
  "sourceMap": pair(asset61Light, asset61Dark),
  "sql": pair(asset62Light, asset62Dark),
  "swiftLang": pair(asset63Light, asset63Dark),
  "terraform": pair(asset64Light, asset64Dark),
  "text": pair(asset65Light, asset65Dark),
  "toml": pair(asset66Light, asset66Dark),
  "typeScript": pair(asset67Light, asset67Dark),
  "uiForm": pair(asset68Light, asset68Dark),
  "unknown": pair(asset69Light, asset69Dark),
  "vue": pair(asset70Light, asset70Light),
  "wsdl": pair(asset71Light, asset71Dark),
  "xhtml": pair(asset72Light, asset72Dark),
  "xml": pair(asset73Light, asset73Dark),
  "xsd": pair(asset74Light, asset74Dark),
  "yaml": pair(asset75Light, asset75Dark),
} as const satisfies Readonly<Record<string, IconAssetSources>>

export type IconAssetId = keyof typeof ICON_ASSETS

export function iconAssetSources(id: IconAssetId): IconAssetSources {
  return ICON_ASSETS[id]
}
